# Meta Data for SEO

## Homepage
title = "Stalwart"
titleSeparator = "-"
titleAddition = "Stalwart Mail Server"
description = "Stalwart is a scalable, secure and fast mail server with JMAP and IMAP support."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["stalwart.png"]
ogLocale = "en_US"
domainTLD = "stalw.art"
titleHome = "Stalwart Labs"

## Twitter Cards
twitterSite = "@stalwartlabs"
twitterCreator = "@stalwartlabs"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Stalwart"
schemaAuthor = "Stalwart Labs Ltd."
schemaAuthorTwitter = "https://twitter.com/stalwartlabs"
#schemaAuthorLinkedIn = "https://www.linkedin.com/in/stalwartlabs/"
schemaAuthorGitHub = "https://github.com/stalwartlabs"
schemaLocale = "en-US"
schemaLogo = "logo-stalwart.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "stalwart.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/stalwartlabs"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/stalwartlabs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "<a class=\"text-muted\" href=\"https://stalw.art/\">Stalwart Labs Ltd.</a> - Made with <span title=\"Rust\">ðŸ¦€</a> in <span title=\"London, United Kingdom\">ðŸ‡¬ðŸ‡§</a>"

# Feed
copyRight = "Copyright (c) Stalwart Labs Ltd."

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
#alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/stalwartlabs/stalwart-website"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = false

[sections]
  sectionNav = ["jmap", "imap"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = true
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
